name: Deploy via FTPS to SiteGround
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SG_FTPS_SERVER }}
          username: ${{ secrets.SG_FTPS_USERNAME }}
          password: ${{ secrets.SG_FTPS_PASSWORD }}
          protocol: ftps
          port: 21
          # your new FTP user is chrooted to the subdomain root, so deploy to /
          server-dir: /
          local-dir: ./
          dangerous-clean-slate: false
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
