name: Deploy to SiteGround (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Preflight: fail fast if any secret is missing
      - name: Preflight secrets
        shell: bash
        run: |
          missing=0
          [ -n "${{ secrets.SG_SERVER }}" ] || { echo "❌ Missing SG_SERVER"; missing=1; }
          [ -n "${{ secrets.SG_PORT }}" ] || { echo "❌ Missing SG_PORT"; missing=1; }
          [ -n "${{ secrets.SG_USERNAME }}" ] || { echo "❌ Missing SG_USERNAME"; missing=1; }
          [ -n "${{ secrets.SG_KEY }}" ] || { echo "❌ Missing SG_KEY"; missing=1; }
          [ -n "${{ secrets.SG_REMOTE_PATH }}" ] || { echo "❌ Missing SG_REMOTE_PATH"; missing=1; }
          if [ "$missing" -eq 1 ]; then
            echo "Fix the missing secrets in Settings → Secrets and rerun."; exit 1
          fi
          echo "✅ All secrets present."

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SG_SERVER }}
          port: ${{ secrets.SG_PORT }}
          username: ${{ secrets.SG_USERNAME }}
          ssh_private_key: ${{ secrets.SG_KEY }}
          local_path: "./"
          remote_path: ${{ secrets.SG_REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false
          # leave password and sftpArgs blank
