name: Deploy via SFTP

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to SiteGround via SFTP
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
          REMOTE_HOST: gcam1050.siteground.biz
          REMOTE_USER: u2212-6q1dxbl4nmbd
          REMOTE_PORT: 18765
          SOURCE: ./
          TARGET: /home/customer/www/vote.earnyourencorekaraoke.com/public_html/
          ARGS: "-avz --delete"
