name: Deploy via FTPS to SiteGround

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SG_FTPS_SERVER }}
          username: ${{ secrets.SG_FTPS_USERNAME }}
          password: ${{ secrets.SG_FTPS_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /www/vote.earnyourencorekaraoke.com/public_html
          local-dir: ./
          # keeps .git and .github from uploading; add more patterns if you want
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
          log-level: verbose
