name: Deploy to SiteGround (SFTP)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SFTP Deploy (with PASSWORD)
        if: ${{ secrets.SG_PASSWORD != '' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SG_HOST }}
          port: 22
          username: ${{ secrets.SG_USER }}
          password: ${{ secrets.SG_PASSWORD }}
          local_path: "./"
          remote_path: ${{ secrets.SG_REMOTE_PATH }}
          sftp_only: true
          # set to 'true' only if you want the action to
          # remove files on the server that don't exist locally
          delete_remote_files: false

      - name: SFTP Deploy (with SSH KEY)
        if: ${{ secrets.SG_PASSWORD == '' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SG_HOST }}
          port: 22
          username: ${{ secrets.SG_USER }}
          ssh_private_key: ${{ secrets.SG_KEY }}
          local_path: "./"
          remote_path: ${{ secrets.SG_REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false
