name: Deploy to SiteGround via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Add a build step if needed
      # - name: Build project
      #   run: npm install && npm run build

      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_HOST }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PORT: ${{ secrets.SFTP_PORT }}
          SOURCE: ./dist
          TARGET: ${{ secrets.SFTP_PATH }}
