name: Deploy to SiteGround (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write private key to file
        run: |
          umask 077
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SG_SSH_KEY }}" > $HOME/.ssh/sg_key
          chmod 600 $HOME/.ssh/sg_key

      - name: SFTP deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SG_HOST }}
          port: ${{ secrets.SG_PORT }}
          username: ${{ secrets.SG_USER }}
          ssh_private_key: $HOME/.ssh/sg_key
          local_path: ./
          remote_path: ${{ secrets.SG_REMOTE_PATH }}
          sftp_only: true
          delete_remote_files: false
