name: Deploy to SiteGround (SFTP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SG_SERVER }}
          port: ${{ secrets.SG_PORT }}
          username: ${{ secrets.SG_USERNAME }}
          ssh_private_key: ${{ secrets.SG_SSH_KEY }}
          local_path: "./"
          remote_path: "/home/customer/www/vote.earnyourencorekaraoke.com/public_html"
          sftp_only: true
          delete_remote_files: false
          sftpArgs: "-o StrictHostKeyChecking=no"
