name: Deploy via FTPS to SiteGround (vote subdomain)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: siteground-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to SiteGround (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # === Use the SAME values that work in FileZilla ===
          server: ${{ secrets.SG_FTPS_SERVER }}      # e.g. gcam1050.siteground.biz
          username: ${{ secrets.SG_FTPS_USERNAME }}  # your working FileZilla username
          password: ${{ secrets.SG_FTPS_PASSWORD }}  # your working FileZilla password
          protocol: ftps
          port: 21

          # Your confirmed directory. MUST end with a slash:
          server-dir: /vote.earnyourencorekaraoke.com/public_html/

          # Upload the whole repo (minus exclusions below)
          local-dir: ./

          # Don’t upload Git/GitHub stuff, node modules, etc.
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.vscode/**
            **/.DS_Store
            **/README.md
            **/LICENSE

          log-level: verbose
