name: Deploy via FTPS to SiteGround
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Upload everything in the repo to your subdomain's document root
      - name: Deploy with FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: gcam1050.siteground.biz
          username: tom@earnyourencorekaraoke.com
          password: ${{ secrets.SG_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: /home/customer/www/vote.earnyourencorekaraoke.com/public_html/
          dangerous-clean-slate: false
          log-level: verbose
