name: Probe SiteGround SFTP
on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    env:
      # These three are NOT secrets
      SG_HOST: gcam1050.siteground.biz
      SG_PORT: "18765"
      SG_USERNAME: u2212-6q1dxbl4nmbd
      SG_REMOTE_PATH: /home/customer/www/vote.earnyourencorekaraoke.com/public_html
      # This one IS the secret (private key, base64-encoded)
      SG_SSH_KEY_B64: ${{ secrets.SG_SSH_KEY_B64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show non-secret settings
        run: |
          echo "HOST=$SG_HOST"
          echo "PORT=$SG_PORT"
          echo "USER=$SG_USERNAME"
          echo "REMOTE=$SG_REMOTE_PATH"

      - name: Install openssh client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Prepare ~/.ssh
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "$SG_SSH_KEY_B64" | base64 -d > ~/.ssh/sg_key
          chmod 600 ~/.ssh/sg_key
          # trust the SG host key to avoid an interactive prompt
          ssh-keyscan -p "$SG_PORT" "$SG_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Probe SFTP (verbose)
        run: |
          set -x
          sftp -vvv -P "$SG_PORT" -i ~/.ssh/sg_key "$SG_USERNAME@$SG_HOST" <<EOF
          pwd
          ls -la
          cd www
          ls -la
          cd vote.earnyourencorekaraoke.com/public_html
          pwd
          ls -la
          bye
          EOF
