name: Probe SiteGround SFTP

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (not strictly needed, but harmless)
        uses: actions/checkout@v4

      - name: Write private key
        run: |
          umask 077
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SG_SSH_KEY }}" > "$HOME/.ssh/sg_key"
          chmod 600 "$HOME/.ssh/sg_key"

      - name: Create probe file
        run: |
          echo "probe $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > PROBE.txt
          ls -l PROBE.txt

      - name: SFTP list + put + list + delete
        shell: bash
        env:
          HOST: ${{ secrets.SG_HOST }}
          PORT: ${{ secrets.SG_PORT }}
          USER: ${{ secrets.SG_USER }}
          REMOTE: ${{ secrets.SG_REMOTE_PATH }}
        run: |
          set -euo pipefail
          echo "=== Using host:$HOST port:$PORT user:$USER remote:$REMOTE ==="

          # Show remote PWD and list parent + remote dir
          /usr/bin/sftp -o StrictHostKeyChecking=no -P "$PORT" -i "$HOME/.ssh/sg_key" "$USER@$HOST" <<SFTP_CMDS
          pwd
          ls -la
          cd $REMOTE
          pwd
          ls -la
          put PROBE.txt
          ls -la
          rm PROBE.txt
          ls -la
          bye
          SFTP_CMDS
